export enum Action {
    CONTEXT_APP_INIT = 'CONTEXT_APP_INIT',
    ENLARGE_EN_TEXT_FONT_SIZE_OF_THE_LIST = 'ENLARGE_EN_TEXT_FONT_SIZE_OF_THE_LIST',
    GAME_CONTROLLER_CONNECTION_CHECK = 'GAME_CONTROLLER_CONNECTION_CHECK',
    GAME_CONTROLLER_CONNECTION_SUCCESS = 'GAME_CONTROLLER_CONNECTION_SUCCESS'
}